---
title: "STAT 457, A4Q4"
subtitle: Yun Kyaw, 20177325
date: "2023-04-05"
output:
  word_document: default
  pdf_document: default
---
#### C) Let the design matrix X be given in the file A4Q4.csv, and the response vector Y in the file A4Q4.csv; in particular, n = 600, and p = 15. Write your own Newton-Raphson algorithm to find the minimizer of $\Phi$.  

```{r setup, include=FALSE}
library(readr)
A4Q4_X <- read_csv("A4Q4_X.csv")
A4Q4_Y <- read_csv("A4Q4_Y.csv")
```

```{r}
# using glm
glmData = cbind.data.frame(A4Q4_X, A4Q4_Y)

beta_glm = glm(Y~., data = glmData, family=binomial)
```

``` {r}
# Creating the Newton-Raphson algorithm function
NewtonRaphson <- function(X, Y, maxIter, epsilon, lambda = 1){
  n = 600
  #initialization for beta and W used in computing grad and Hessain
  beta_nr = rep(0, ncol(X))
  W_old = matrix(0, n, n)
  for(id in 1:maxIter){#run at most 10000 steps
    beta_old = beta_nr
    
    p_old = exp(X %*% beta_old)/(1+exp(X %*% beta_old))
    diag(W_old) = p_old * (1 - p_old) #change the diag
    
    #compute the grad and Hessian
    tmp_grad = (-1/n) * (t(X) %*% (Y - p_old)) + (lambda * beta_old)
    tmp_Hes = (1/n) * (-t(X) %*% W_old %*% X) + lambda
    beta_nr = beta_old + solve(tmp_Hes) %*% tmp_grad
    
    if(mean(sqrt((beta_nr-beta_old)^2)) <= epsilon){
      break
    }
  }
  return(beta_nr)
}
```

```{r}
# performing the Newton-Raphson algorithm
n = 600
X = as.matrix(A4Q4_X)
Y = as.matrix(A4Q4_Y)
beta_nr = NewtonRaphson(X,Y,1e-8, 10^4)
```

```{r}
# verifying the accuracy of the Newton-Raphson algorithm
mse = 1/15 * sum((beta_nr - beta_glm$coefficients[2:16])^2)  # exclude the intercept in glm
mse
```
Thus, from performing calculating the MSE, we find that the function performs relatively well, considering there is a small MSE of roughly 0.18.
